FROM python:3.12-slim

RUN apt-get update && apt-get install -y libfaketime

WORKDIR /app
COPY . .
RUN pip install poetry && poetry install

# This env variable tells faketime what time to "spoof"
ENV LD_PRELOAD=libfaketime.so.1
